const top50Countries = [
    { label: 'United States (+1)', name: 'United States', code: '+1' },
    { label: 'Canada (+2)', name: 'Canada', code: '+2' },
    { label: 'United Kingdom (+44)', name: 'United Kingdom', code: '+44' },
    { label: 'Australia (+61)', name: 'Australia', code: '+61' },
    { label: 'Germany (+49)', name: 'Germany', code: '+49' },
    { label: 'France (+33)', name: 'France', code: '+33' },
    { label: 'Brazil (+55)', name: 'Brazil', code: '+55' },
    { label: 'India (+91)', name: 'India', code: '+91' },
    { label: 'China (+86)', name: 'China', code: '+86' },
    { label: 'Japan (+81)', name: 'Japan', code: '+81' },
    { label: 'South Korea (+82)', name: 'South Korea', code: '+82' },
    { label: 'Mexico (+52)', name: 'Mexico', code: '+52' },
    { label: 'Spain (+34)', name: 'Spain', code: '+34' },
    { label: 'Italy (+39)', name: 'Italy', code: '+39' },
    { label: 'Netherlands (+31)', name: 'Netherlands', code: '+31' },
    { label: 'South Africa (+27)', name: 'South Africa', code: '+27' },
    { label: 'Russia (+7)', name: 'Russia', code: '+7' },
    { label: 'Sweden (+46)', name: 'Sweden', code: '+46' },
    { label: 'Norway (+47)', name: 'Norway', code: '+47' },
    { label: 'Switzerland (+41)', name: 'Switzerland', code: '+41' },
    { label: 'New Zealand (+64)', name: 'New Zealand', code: '+64' },
    { label: 'Singapore (+65)', name: 'Singapore', code: '+65' },
    { label: 'Argentina (+54)', name: 'Argentina', code: '+54' },
    { label: 'Chile (+56)', name: 'Chile', code: '+56' },
    { label: 'Egypt (+20)', name: 'Egypt', code: '+20' },
    { label: 'Turkey (+90)', name: 'Turkey', code: '+90' },
    { label: 'Greece (+30)', name: 'Greece', code: '+30' },
    { label: 'Thailand (+66)', name: 'Thailand', code: '+66' },
    { label: 'Malaysia (+60)', name: 'Malaysia', code: '+60' },
    { label: 'Saudi Arabia (+966)', name: 'Saudi Arabia', code: '+966' },
    { label: 'United Arab Emirates (+971)', name: 'United Arab Emirates', code: '+971' },
    { label: 'Israel (+972)', name: 'Israel', code: '+972' },
    { label: 'Pakistan (+92)', name: 'Pakistan', code: '+92' },
    { label: 'Bangladesh (+880)', name: 'Bangladesh', code: '+880' },
    { label: 'Indonesia (+62)', name: 'Indonesia', code: '+62' },
    { label: 'Philippines (+63)', name: 'Philippines', code: '+63' },
    { label: 'Vietnam (+84)', name: 'Vietnam', code: '+84' },
    { label: 'Peru (+51)', name: 'Peru', code: '+51' },
    { label: 'Colombia (+57)', name: 'Colombia', code: '+57' },
    { label: 'Nigeria (+234)', name: 'Nigeria', code: '+234' },
    { label: 'Kenya (+254)', name: 'Kenya', code: '+254' },
    { label: 'South Africa (+27)', name: 'South Africa', code: '+27' },
    { label: 'Morocco (+212)', name: 'Morocco', code: '+212' },
    { label: 'Algeria (+213)', name: 'Algeria', code: '+213' },
    { label: 'Tunisia (+216)', name: 'Tunisia', code: '+216' },
    { label: 'Ghana (+233)', name: 'Ghana', code: '+233' },
    { label: 'Nigeria (+234)', name: 'Nigeria', code: '+234' },
  ];
  
  export default top50Countries;
  